services:
  aiforge:
    build:
      context: .
      args:
        - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
        - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
        - AIFORGE_LOCALE=${AIFORGE_LOCALE}
        - SEARXNG_ENABLED=${SEARXNG_ENABLED}
        - SEARXNG_LOCAL_URL=${SEARXNG_LOCAL_URL}
        - SEARXNG_REMOTE_URL=${SEARXNG_REMOTE_URL}
        - SEARXNG_FALLBACK_TO_PUBLIC=${SEARXNG_FALLBACK_TO_PUBLIC}
    container_name: aiforge-engine
    ports:
      - "${AIFORGE_WEB_PORT:-8000}:8000"
    volumes:
      - ./aiforge_work:/app/aiforge_work
      - ./logs:/app/logs
    environment:
      # Docker环境标识
      - AIFORGE_DOCKER_MODE=true

      # API配置 (Docker层)
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://host.docker.internal:11434}

      # 基础应用配置
      - AIFORGE_MAX_TOKENS=${AIFORGE_MAX_TOKENS:-4096}
      - AIFORGE_MAX_ROUNDS=${AIFORGE_MAX_ROUNDS:-5}
      - AIFORGE_DEFAULT_PROVIDER=${AIFORGE_DEFAULT_PROVIDER:-openrouter}
      - AIFORGE_LOCALE=${AIFORGE_LOCALE:-en}

      # 可选搜索服务配置 (Docker层)
      - SEARXNG_ENABLED=${SEARXNG_ENABLED:-false}
      - SEARXNG_LOCAL_URL=${SEARXNG_LOCAL_URL}
      - SEARXNG_REMOTE_URL=${SEARXNG_REMOTE_URL}
      - SEARXNG_FALLBACK_TO_PUBLIC=${SEARXNG_FALLBACK_TO_PUBLIC:-true}
    # 移除对 nginx 的硬依赖
    networks:
      - aiforge-network
    restart: unless-stopped
    command: ["web"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  searxng:
    image: searxng/searxng:latest
    container_name: aiforge-searxng
    expose:
      - "8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    networks:
      - aiforge-network
    restart: unless-stopped
    profiles: ["searxng"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: aiforge-nginx
    ports:
      - "55510:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - searxng
    networks:
      - aiforge-network
    restart: unless-stopped
    profiles: ["searxng"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  # CLI服务简化
  aiforge-cli:
    build: .
    container_name: aiforge-cli
    volumes:
      - ./aiforge_work:/app/aiforge_work
      - ./config:/app/config
    environment:
      - AIFORGE_DOCKER_MODE=true
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - AIFORGE_LOCALE=${AIFORGE_LOCALE}
      - SEARXNG_ENABLED=${SEARXNG_ENABLED}
      - SEARXNG_LOCAL_URL=${SEARXNG_LOCAL_URL}
      - SEARXNG_REMOTE_URL=${SEARXNG_REMOTE_URL}
      - SEARXNG_FALLBACK_TO_PUBLIC=${SEARXNG_FALLBACK_TO_PUBLIC}
    networks:
      - aiforge-network
    profiles: ["cli"]
    command: ["cli", "--help"]

networks:
  aiforge-network:
    driver: bridge
